name: Build Android APK from ZIP

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip -o "BlurGuard-Android-Starter.zip" -d .
          ls -la

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      # نستخدم Gradle بدون wrapper (أنا جهزته لك بهالإعداد)
      - name: Build Debug APK (assembleDebug)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: "8.7"
          arguments: assembleDebug
          build-root-directory: .

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: BlurGuard-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
